services:
  # database:
  #   container_name: database
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_DB: "MonitorDevices"
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "47QUv7J6bR31"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432

  # api:
  #   container_name: backend
  #   build: ./backend
  #   image: backend:1.0.0
  #   restart: always
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   volumes:
  #     - api-data:/var/lib/data
  #   # depends_on:
  #   #   - database
  #   ports:
  #     - 10001:8080

  web:
    container_name: frontend
    build: ./frontend
    image: frontend:1.0.0
    restart: always
    ports:
      - 10002:5173
    # depends_on:
    #   - api

# volumes:
#   api-data:
#   postgres-data: